- name: "Installing tools from apt"
  package:
    name:
      - pipenv
      - jq
      - ripgrep
    state: present
  become: true

- name: "Uninstalling unwanted tools"
  package:
    name:
      - hashcat
      - python3-impacket
      - impacket-scripts
    state: absent
  become: true