---
- name: "Building Parrot"
  hosts: localhost
  connection: local

  roles:
    - role: "update-system"
    - role: "clone-dotfiles"
    - role: "install-zsh"
    - role: "install-tmux"
    - role: "configure-terminal"
    - role: "configure-firefox"
    - role: "install-tools"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - akamud.vscode-theme-onedark
            - KevinRose.vsc-python-indent
            - vscodevim.vim
            - tomoki1207.pdf
            - mechatroner.rainbow-csv
            - tamasfe.even-better-toml
            - ms-python.python