---
- name: "Checking for zshrc"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc_check
- name: "Backing up zshrc"
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc.bak"
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
  when: zshrc_check.stat.exists
- name: "Installing prerequisites"
  apt:
    name:
      - zsh
      - curl
      - git
    state: present
  become: true
  become_method: sudo
- name: "Checking for oh-my-zsh installation"
  ansible.builtin.stat:
    path: "/home/{{ ansible_env.USER }}/.oh-my-zsh"
  register: oh_my_zsh_install_check
- name: "Downloading and installing Oh-My-Zsh"
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s -- --unattended
  args:
    creates: "/home/{{ ansible_env.USER }}/.oh-my-zsh"
- name: "Setting zsh as the default shell"
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes