---
# VS Code extensions to install
vscode_extensions:
  - akamud.vscode-theme-onedark
  - KevinRose.vsc-python-indent
  - vscodevim.vim
  - tomoki1207.pdf
  - mechatroner.rainbow-csv
  - tamasfe.even-better-toml
  - ms-python.python

# VS Code user configuration - Required for gantsign.visual-studio-code role
users:
  - username: "{{ ansible_user_id }}"
    visual_studio_code_extensions: "{{ vscode_extensions }}"